import Link from 'next/link';
export function HomeSections(){return <>
<section className="section"><div className="container grid gap-6 md:grid-cols-3"><div className="rounded-3xl border border-white/10 bg-white/[.04] p-7"><p className="text-cyan-300">01</p><h3 className="mt-5 text-xl font-semibold">Learn by doing</h3><p className="mt-3 text-sm leading-6 text-slate-400">Move from concepts to practical work instead of collecting theory alone.</p></div><div className="rounded-3xl border border-white/10 bg-white/[.04] p-7"><p className="text-cyan-300">02</p><h3 className="mt-5 text-xl font-semibold">Build real projects</h3><p className="mt-3 text-sm leading-6 text-slate-400">Courses are designed around hands-on outputs you can understand, improve and showcase.</p></div><div className="rounded-3xl border border-white/10 bg-white/[.04] p-7"><p className="text-cyan-300">03</p><h3 className="mt-5 text-xl font-semibold">Keep progressing</h3><p className="mt-3 text-sm leading-6 text-slate-400">A connected learning platform can grow with your skills, assessments and future goals.</p></div></div></section>
<section className="section border-y border-white/10 bg-white/[.02]"><div className="container grid gap-12 md:grid-cols-2"><div><p className="eyebrow">Why BlazeByte</p><h2 className="section-title">Technology education with a practical edge.</h2></div><div className="grid gap-5 text-sm leading-6 text-slate-400"><p><b className="text-white">Practical learning.</b> Focus on usable skills and clear outcomes.</p><p><b className="text-white">Project-based learning.</b> Turn lessons into tangible work.</p><p><b className="text-white">AI-assisted learning.</b> Prepare for the tools shaping modern workflows.</p><p><b className="text-white">Career-focused skills.</b> Build capabilities that translate beyond a single course.</p><p><b className="text-white">Beginner-friendly.</b> Clear progression without unnecessary complexity.</p><p><b className="text-white">Community and support.</b> Learning becomes stronger when questions and progress have a place to live.</p></div></div></section>
<section className="section"><div className="container"><p className="eyebrow">Student outcomes</p><div className="mt-8 grid gap-5 md:grid-cols-4"><div className="stat">Understand <span>core concepts</span></div><div className="stat">Build <span>practical projects</span></div><div className="stat">Practice <span>real workflows</span></div><div className="stat">Grow <span>with confidence</span></div></div></div></section>
<section className="section"><div className="container grid gap-10 md:grid-cols-2"><div><p className="eyebrow">Learner stories</p><h2 className="section-title">Real voices, when the data is ready.</h2><p className="mt-4 text-slate-400">We do not publish invented testimonials or student results. Approved reviews from the platform will appear here as they are collected.</p></div><div className="rounded-3xl border border-dashed border-white/15 p-8 text-sm text-slate-500">No approved testimonials yet.</div></div></section>
<section className="section"><div className="container max-w-4xl"><p className="eyebrow">FAQ</p><div className="mt-8 divide-y divide-white/10 rounded-3xl border border-white/10"><details className="p-6"><summary className="cursor-pointer font-semibold">Are courses beginner-friendly?</summary><p className="mt-3 text-sm leading-6 text-slate-400">Each course publishes its level and requirements so you can choose the right starting point.</p></details><details className="p-6"><summary className="cursor-pointer font-semibold">Are the courses project-based?</summary><p className="mt-3 text-sm leading-6 text-slate-400">The platform is designed around practical, project-oriented learning.</p></details><details className="p-6"><summary className="cursor-pointer font-semibold">Will my progress be saved?</summary><p className="mt-3 text-sm leading-6 text-slate-400">Enrolled learning is designed to track lesson progress through your student account.</p></details></div></div></section>
<section className="section"><div className="container"><div className="rounded-[2rem] bg-cyan-300 p-8 text-slate-950 md:p-12"><h2 className="max-w-2xl text-3xl font-bold md:text-5xl">Ready to build your next skill?</h2><p className="mt-4 max-w-xl text-slate-800">Explore the available courses and choose a practical learning path.</p><Link href="/courses" className="mt-7 inline-flex rounded-xl bg-slate-950 px-5 py-3 font-semibold text-white">Explore Courses</Link></div></div></section>
</>}
